# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',     url: 'about.html'}
- {name: 'Posts',     url: 'writing.html'}
- {name: 'Resources', url: 'resources.html'}
- {name: 'CV',        url: 'resume.html'}

social:
- {icon: 'github',     link: 'https://www.github.com/nick-voisin'}
- {icon: 'twitter',    link: 'https://twitter.com/NickVoisin'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/voisinnicolas/'}
- {icon: 'envelope',   link: 'mailto:voisin.nicolas@gmail.com'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'
